# Iqra Naeem 18B-037-CS-B -- CLASS TASK 2

In [1]:
import sqlite3
import pandas as pd
import os
print(os.path.abspath('../'))
file_path = os.path.abspath('../../lab 6/database_sql_class Activity/')
print(file_path)
conn = sqlite3.connect(file_path+'/income_analytics.db')

C:\Users\HP\Desktop\Lab 6
C:\Users\HP\Desktop\lab 6\database_sql_class Activity

In [2]:
pd.read_sql_query('select * from income_train', conn)

,ID,Age,Workclass,Education,Marital.Status,Occupation,Relationship,Race,Sex,Hours.Per.Week,Native.Country,Income.Group
0,1,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K
1,2,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K
2,3,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K
3,4,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K
4,5,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K
5,6,37,Private,Masters,Married-civ-spouse,Exec-managerial,Wife,White,Female,40,United-States,<=50K
6,7,49,Private,9th,Married-spouse-absent,Other-service,Not-in-family,Black,Female,16,Jamaica,<=50K
7,8,52,Self-emp-not-inc,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,45,United-States,>50K
8,9,31,Private,Masters,Never-married,Prof-specialty,Not-in-family,White,Female,50,United-States,>50K
9,10,42,Private,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,40,United-States,>50K
10,11,37,Private,Some-college,Married-civ-spouse,Exec-managerial,Husband,Black,Male,80,United-States,>50K
11,12,30,State-gov,Bachelors,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,40,India,>50K
12,13,23,Private,Bachelors,Never-married,Adm-clerical,Own-child,White,Female,30,United-States,<=50K
13,14,32,Private,Assoc-acdm,Never-married,Sales,Not-in-family,Black,Male,50,United-States,<=50K
14,15,40,Private,Assoc-voc,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,40,None,>50K
15,16,34,Private,7th-8th,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,45,Mexico,<=50K
16,17,25,Self-emp-not-inc,HS-grad,Never-married,Farming-fishing,Own-child,White,Male,35,United-States,<=50K
17,18,32,Private,HS-grad,Never-married,Machine-op-inspct,Unmarried,White,Male,40,United-States,<=50K
18,19,38,Private,11th,Married-civ-spouse,Sales,Husband,White,Male,50,United-States,<=50K
19,20,43,Self-emp-not-inc,Masters,Divorced,Exec-managerial,Unmarried,White,Female,45,United-States,>50K
20,21,40,Private,Doctorate,Married-civ-spouse,Prof-specialty,Husband,White,Male,60,United-States,>50K
21,22,54,Private,HS-grad,Separated,Other-service,Unmarried,Black,Female,20,United-States,<=50K
22,23,35,Federal-gov,9th,Married-civ-spouse,Farming-fishing,Husband,Black,Male,40,United-States,<=50K
23,24,43,Private,11th,Married-civ-spouse,Transport-moving,Husband,White,Male,40,United-States,<=50K
24,25,59,Private,HS-grad,Divorced,Tech-support,Unmarried,White,Female,40,United-States,<=50K
25,26,56,Local-gov,Bachelors,Married-civ-spouse,Tech-support,Husband,White,Male,40,United-States,>50K
26,27,19,Private,HS-grad,Never-married,Craft-repair,Own-child,White,Male,40,United-States,<=50K
27,28,54,None,Some-college,Married-civ-spouse,None,Husband,Asian-Pac-Islander,Male,60,South,>50K
28,29,39,Private,HS-grad,Divorced,Exec-managerial,Not-in-family,White,Male,80,United-States,<=50K
29,30,49,Private,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...
32531,32532,30,None,Bachelors,Never-married,None,Not-in-family,Asian-Pac-Islander,Female,99,United-States,<=50K
32532,32533,34,Private,Doctorate,Married-civ-spouse,Prof-specialty,Husband,White,Male,60,United-States,>50K
32533,32534,54,Private,Bachelors,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,50,Japan,>50K
32534,32535,37,Private,Some-college,Divorced,Adm-clerical,Unmarried,White,Female,39,United-States,<=50K
32535,32536,22,Private,12th,Never-married,Protective-serv,Own-child,Black,Male,35,United-States,<=50K
32536,32537,34,Private,Bachelors,Never-married,Exec-managerial,Not-in-family,White,Female,55,United-States,>50K
32537,32538,30,Private,HS-grad,Never-married,Craft-repair,Not-in-family,Black,Male,46,United-States,<=50K
32538,32539,38,Private,Bachelors,Divorced,Prof-specialty,Unmarried,Black,Female,45,United-States,>50K
32539,32540,71,None,Doctorate,Married-civ-spouse,None,Husband,White,Male,10,United-States,>50K
32540,32541,45,State-gov,HS-grad,Separated,Adm-clerical,Own-child,White,Female,40,United-States,<=50K
32541,32542,41,None,HS-grad,Separated,None,Not-in-family,Black,Female,32,United-States,<=50K
32542,32543,72,None,HS-grad,Married-civ-spouse,None,Husband,White,Male,25,United-States,<=50K
32543,32544,45,Local-gov,Assoc-acdm,Divorced,Prof-specialty,Unmarried,White,Female,48,United-States,<=50K
32544,32545,31,Private,Masters,Divorced,Other-service,Not-in-family,Other,Female,30,United-States,<=50K
32545,32546,39,Local-gov,Assoc-acdm,Married-civ-spouse,Adm-clerical,Wife,White,Female,20,United-States,>50K
32546,32547,37,Private,Assoc-acdm,Divorced,Tech-support,Not-in-family,White,Female,40,United-States,<=50K
32547,32548,43,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,Mexico,<=50K
32548,32549,65,Self-emp-not-inc,Prof-school,Never-married,Prof-specialty,Not-in-family,White,Male,60,United-States,<=50K
32549,32550,43,State-gov,Some-college,Divorced,Adm-clerical,Other-relative,White,Female,40,United-States,<=50K
32550,32551,43,Self-emp-not-inc,Some-college,Married-civ-spouse,Craft-repair,Husband,White,Male,50,United-States,<=50K
32551,32552,32,Private,10th,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,40,United-States,<=50K
32552,32553,43,Private,Assoc-voc,Married-civ-spouse,Sales,Husband,White,Male,45,United-States,<=50K
32553,32554,32,Private,Masters,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,11,Taiwan,<=50K
32554,32555,53,Private,Masters,Married-civ-spouse,Exec-managerial,Husband,White,Male,40,United-States,>50K
32555,32556,22,Private,Some-college,Never-married,Protective-serv,Not-in-family,White,Male,40,United-States,<=50K
32556,32557,27,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,38,United-States,<=50K
32557,32558,40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,>50K
32558,32559,58,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,40,United-States,<=50K
32559,32560,22,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,20,United-States,<=50K
32560,32561,52,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,40,United-States,>50K

In [3]:
pd.read_sql_query('select * from income_train limit 5' , conn)

,ID,Age,Workclass,Education,Marital.Status,Occupation,Relationship,Race,Sex,Hours.Per.Week,Native.Country,Income.Group
0,1,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K
1,2,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K
2,3,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K
3,4,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K
4,5,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K

In [4]:
#get dimensions of your data
query = 'select count(*) from income_train'
pd.read_sql_query(query,conn)

   count(*)
0     32561

# VARIABLE TYPES

In [ ]:
#pragma function is used to provide instruction to the compiler

In [5]:
query = 'PRAGMA table_info(income_train)'
pd.read_sql_query(query,conn)

    cid            name     type  notnull dflt_value  pk
0     0              ID  INTEGER        0       None   0
1     1             Age  INTEGER        0       None   0
2     2       Workclass     TEXT        0       None   0
3     3       Education     TEXT        0       None   0
4     4  Marital.Status     TEXT        0       None   0
5     5      Occupation     TEXT        0       None   0
6     6    Relationship     TEXT        0       None   0
7     7            Race     TEXT        0       None   0
8     8             Sex     TEXT        0       None   0
9     9  Hours.Per.Week  INTEGER        0       None   0
10   10  Native.Country     TEXT        0       None   0
11   11    Income.Group     TEXT        0       None   0

# CATEGORICAL VARIABLES

In [6]:
query = 'PRAGMA table_info(income_train)'
df3 = pd.read_sql_query(query,conn)
df3[df3['type'] == 'TEXT']

    cid            name  type  notnull dflt_value  pk
2     2       Workclass  TEXT        0       None   0
3     3       Education  TEXT        0       None   0
4     4  Marital.Status  TEXT        0       None   0
5     5      Occupation  TEXT        0       None   0
6     6    Relationship  TEXT        0       None   0
7     7            Race  TEXT        0       None   0
8     8             Sex  TEXT        0       None   0
10   10  Native.Country  TEXT        0       None   0
11   11    Income.Group  TEXT        0       None   0

# Filter in SQL - Using WHERE clause

In [7]:
# Get all records of gender 'Male'
query = 'select * from income_train where sex = "Male"'
pd.read_sql_query(query,conn)

,ID,Age,Workclass,Education,Marital.Status,Occupation,Relationship,Race,Sex,Hours.Per.Week,Native.Country,Income.Group
0,1,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K
1,2,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K
2,3,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K
3,4,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K
4,8,52,Self-emp-not-inc,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,45,United-States,>50K
5,10,42,Private,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,40,United-States,>50K
6,11,37,Private,Some-college,Married-civ-spouse,Exec-managerial,Husband,Black,Male,80,United-States,>50K
7,12,30,State-gov,Bachelors,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,40,India,>50K
8,14,32,Private,Assoc-acdm,Never-married,Sales,Not-in-family,Black,Male,50,United-States,<=50K
9,15,40,Private,Assoc-voc,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,40,None,>50K
10,16,34,Private,7th-8th,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,45,Mexico,<=50K
11,17,25,Self-emp-not-inc,HS-grad,Never-married,Farming-fishing,Own-child,White,Male,35,United-States,<=50K
12,18,32,Private,HS-grad,Never-married,Machine-op-inspct,Unmarried,White,Male,40,United-States,<=50K
13,19,38,Private,11th,Married-civ-spouse,Sales,Husband,White,Male,50,United-States,<=50K
14,21,40,Private,Doctorate,Married-civ-spouse,Prof-specialty,Husband,White,Male,60,United-States,>50K
15,23,35,Federal-gov,9th,Married-civ-spouse,Farming-fishing,Husband,Black,Male,40,United-States,<=50K
16,24,43,Private,11th,Married-civ-spouse,Transport-moving,Husband,White,Male,40,United-States,<=50K
17,26,56,Local-gov,Bachelors,Married-civ-spouse,Tech-support,Husband,White,Male,40,United-States,>50K
18,27,19,Private,HS-grad,Never-married,Craft-repair,Own-child,White,Male,40,United-States,<=50K
19,28,54,None,Some-college,Married-civ-spouse,None,Husband,Asian-Pac-Islander,Male,60,South,>50K
20,29,39,Private,HS-grad,Divorced,Exec-managerial,Not-in-family,White,Male,80,United-States,<=50K
21,30,49,Private,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,40,United-States,<=50K
22,31,23,Local-gov,Assoc-acdm,Never-married,Protective-serv,Not-in-family,White,Male,52,United-States,<=50K
23,32,20,Private,Some-college,Never-married,Sales,Own-child,Black,Male,44,United-States,<=50K
24,33,45,Private,Bachelors,Divorced,Exec-managerial,Own-child,White,Male,40,United-States,<=50K
25,34,30,Federal-gov,Some-college,Married-civ-spouse,Adm-clerical,Own-child,White,Male,40,United-States,<=50K
26,35,22,State-gov,Some-college,Married-civ-spouse,Other-service,Husband,Black,Male,15,United-States,<=50K
27,36,48,Private,11th,Never-married,Machine-op-inspct,Unmarried,White,Male,40,Puerto-Rico,<=50K
28,37,21,Private,Some-college,Never-married,Machine-op-inspct,Own-child,White,Male,40,United-States,<=50K
29,39,31,Private,Some-college,Married-civ-spouse,Sales,Husband,White,Male,38,None,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...
21760,32507,38,Private,Assoc-voc,Married-civ-spouse,Craft-repair,Husband,White,Male,55,United-States,>50K
21761,32508,50,Private,Bachelors,Married-civ-spouse,Prof-specialty,Husband,White,Male,40,United-States,<=50K
21762,32511,39,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,45,None,>50K
21763,32513,20,Private,HS-grad,Never-married,Machine-op-inspct,Own-child,White,Male,40,United-States,<=50K
21764,32515,40,Private,Assoc-voc,Married-civ-spouse,Craft-repair,Husband,Black,Male,45,United-States,<=50K
21765,32516,66,Federal-gov,10th,Married-civ-spouse,Craft-repair,Husband,White,Male,40,United-States,<=50K
21766,32518,36,Private,7th-8th,Married-civ-spouse,Craft-repair,Husband,White,Male,40,United-States,<=50K
21767,32519,57,Local-gov,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,40,United-States,>50K
21768,32520,46,Private,Some-college,Married-civ-spouse,Exec-managerial,Husband,White,Male,48,United-States,>50K
21769,32522,33,Private,HS-grad,Married-civ-spouse,Craft-repair,Husband,Black,Male,40,United-States,<=50K
21770,32523,58,Private,11th,Married-civ-spouse,Sales,Husband,White,Male,40,United-States,<=50K
21771,32524,30,Private,HS-grad,Divorced,Transport-moving,Not-in-family,White,Male,55,United-States,<=50K
21772,32527,32,Private,10th,Married-civ-spouse,Transport-moving,Husband,White,Male,40,United-States,<=50K
21773,32528,22,Private,Some-college,Never-married,Adm-clerical,Own-child,White,Male,40,United-States,<=50K
21774,32533,34,Private,Doctorate,Married-civ-spouse,Prof-specialty,Husband,White,Male,60,United-States,>50K
21775,32534,54,Private,Bachelors,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,50,Japan,>50K
21776,32536,22,Private,12th,Never-married,Protective-serv,Own-child,Black,Male,35,United-States,<=50K
21777,32538,30,Private,HS-grad,Never-married,Craft-repair,Not-in-family,Black,Male,46,United-States,<=50K
21778,32540,71,None,Doctorate,Married-civ-spouse,None,Husband,White,Male,10,United-States,>50K
21779,32543,72,None,HS-grad,Married-civ-spouse,None,Husband,White,Male,25,United-States,<=50K
21780,32548,43,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,Mexico,<=50K
21781,32549,65,Self-emp-not-inc,Prof-school,Never-married,Prof-specialty,Not-in-family,White,Male,60,United-States,<=50K
21782,32551,43,Self-emp-not-inc,Some-college,Married-civ-spouse,Craft-repair,Husband,White,Male,50,United-States,<=50K
21783,32552,32,Private,10th,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,40,United-States,<=50K
21784,32553,43,Private,Assoc-voc,Married-civ-spouse,Sales,Husband,White,Male,45,United-States,<=50K
21785,32554,32,Private,Masters,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,11,Taiwan,<=50K
21786,32555,53,Private,Masters,Married-civ-spouse,Exec-managerial,Husband,White,Male,40,United-States,>50K
21787,32556,22,Private,Some-college,Never-married,Protective-serv,Not-in-family,White,Male,40,United-States,<=50K
21788,32558,40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,>50K
21789,32560,22,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,20,United-States,<=50K

In [8]:
#SELECT a single column

In [9]:
# print a single value
query = 'select Workclass from income_train'
pd.read_sql_query(query,conn)

              Workclass
0             State-gov
1      Self-emp-not-inc
2               Private
3               Private
4               Private
5               Private
6               Private
7      Self-emp-not-inc
8               Private
9               Private
10              Private
11            State-gov
12              Private
13              Private
14              Private
15              Private
16     Self-emp-not-inc
17              Private
18              Private
19     Self-emp-not-inc
20              Private
21              Private
22          Federal-gov
23              Private
24              Private
25            Local-gov
26              Private
27                 None
28              Private
29              Private
...                 ...
32531              None
32532           Private
32533           Private
32534           Private
32535           Private
32536           Private
32537           Private
32538           Private
32539              None
32540         State-gov
32541              None
32542              None
32543         Local-gov
32544           Private
32545         Local-gov
32546           Private
32547           Private
32548  Self-emp-not-inc
32549         State-gov
32550  Self-emp-not-inc
32551           Private
32552           Private
32553           Private
32554           Private
32555           Private
32556           Private
32557           Private
32558           Private
32559           Private
32560      Self-emp-inc

[32561 rows x 1 columns]

In [10]:
# UNIQUES values DISTINCT

In [11]:
query = 'select distinct(Workclass) from income_train'
pd.read_sql_query(query,conn)

          Workclass
0         State-gov
1  Self-emp-not-inc
2           Private
3       Federal-gov
4         Local-gov
5              None
6      Self-emp-inc
7       Without-pay
8      Never-worked

In [12]:
# SUM in SQL

In [13]:
# print a single value of hours per week 
query = 'select "Hours.Per.Week" from income_train where sex = "Male"'
pd.read_sql_query(query,conn)

       Hours.Per.Week
0                  40
1                  13
2                  40
3                  40
4                  45
5                  40
6                  80
7                  40
8                  50
9                  40
10                 45
11                 35
12                 40
13                 50
14                 60
15                 40
16                 40
17                 40
18                 40
19                 60
20                 80
21                 40
22                 52
23                 44
24                 40
25                 40
26                 15
27                 40
28                 40
29                 38
...               ...
21760              55
21761              40
21762              45
21763              40
21764              45
21765              40
21766              40
21767              40
21768              48
21769              40
21770              40
21771              55
21772              40
21773              40
21774              60
21775              50
21776              35
21777              46
21778              10
21779              25
21780              40
21781              60
21782              50
21783              40
21784              45
21785              11
21786              40
21787              40
21788              40
21789              20

[21790 rows x 1 columns]

In [14]:
# Gathering All Males for a week would accumalate how many hours of work
query = 'select SUM("Hours.Per.Week") from income_train where Sex = "Male"'
pd.read_sql_query(query,conn)

   SUM("Hours.Per.Week")
0                 924508

# GROUP BY

In [16]:
#Gathering all Male and Female for a week would accumalate how many hours of work
query = 'select Sex, SUM("Hours.Per.Week") from income_train GROUP BY Sex'
pd.read_sql_query(query,conn)

      Sex  SUM("Hours.Per.Week")
0  Female                 392176
1    Male                 924508

In [17]:
query = 'select Sex, count(*) from income_train GROUP BY Sex'
pd.read_sql_query(query,conn)

      Sex  count(*)
0  Female     10771
1    Male     21790

# ORDER BY

In [18]:
query = 'select * from income_train ORDER BY "Hours.Per.Week"'
pd.read_sql_query(query,conn)

,ID,Age,Workclass,Education,Marital.Status,Occupation,Relationship,Race,Sex,Hours.Per.Week,Native.Country,Income.Group
0,190,58,State-gov,Doctorate,Married-civ-spouse,Prof-specialty,Husband,White,Male,1,United-States,>50K
1,1037,66,Self-emp-inc,9th,Married-civ-spouse,Exec-managerial,Husband,White,Male,1,None,<=50K
2,1263,69,None,Assoc-voc,Widowed,None,Not-in-family,White,Female,1,United-States,<=50K
3,5591,78,None,HS-grad,Widowed,None,Not-in-family,White,Female,1,United-States,<=50K
4,5633,45,None,Masters,Married-civ-spouse,None,Wife,White,Female,1,United-States,<=50K
5,5767,62,None,Some-college,Married-civ-spouse,None,Wife,White,Female,1,United-States,<=50K
6,5809,76,None,10th,Married-civ-spouse,None,Husband,White,Male,1,United-States,<=50K
7,8448,67,None,Assoc-voc,Widowed,None,Not-in-family,White,Female,1,United-States,<=50K
8,9148,75,None,10th,Widowed,None,Other-relative,Asian-Pac-Islander,Female,1,China,<=50K
9,11452,27,Private,HS-grad,Never-married,Machine-op-inspct,Other-relative,White,Male,1,United-States,<=50K
10,19338,72,None,HS-grad,Married-civ-spouse,None,Husband,Asian-Pac-Islander,Male,1,United-States,<=50K
11,19751,23,Private,HS-grad,Never-married,Craft-repair,Own-child,Asian-Pac-Islander,Male,1,Vietnam,<=50K
12,20073,65,None,HS-grad,Married-civ-spouse,None,Husband,White,Male,1,United-States,>50K
13,20910,77,Self-emp-not-inc,Some-college,Widowed,Adm-clerical,Not-in-family,White,Female,1,United-States,<=50K
14,22961,21,Private,HS-grad,Never-married,Machine-op-inspct,Own-child,Black,Male,1,United-States,<=50K
15,23537,69,None,Some-college,Never-married,None,Not-in-family,White,Male,1,United-States,<=50K
16,24285,57,Self-emp-not-inc,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,1,United-States,<=50K
17,25079,74,Private,10th,Divorced,Other-service,Not-in-family,White,Female,1,United-States,<=50K
18,29753,69,None,Assoc-acdm,Divorced,None,Unmarried,White,Female,1,United-States,<=50K
19,32526,81,None,Assoc-voc,Divorced,None,Unmarried,White,Female,1,None,<=50K
20,78,67,None,10th,Married-civ-spouse,None,Husband,White,Male,2,United-States,<=50K
21,158,71,Self-emp-not-inc,Some-college,Separated,Sales,Unmarried,Black,Male,2,United-States,<=50K
22,1035,76,None,7th-8th,Widowed,None,Not-in-family,White,Male,2,United-States,<=50K
23,1459,76,None,HS-grad,Widowed,None,Not-in-family,Black,Female,2,United-States,<=50K
24,2933,32,None,Assoc-voc,Never-married,None,Unmarried,White,Female,2,United-States,<=50K
25,3292,74,None,7th-8th,Married-civ-spouse,None,Husband,White,Male,2,United-States,<=50K
26,5173,32,None,HS-grad,Married-civ-spouse,None,Wife,White,Female,2,United-States,>50K
27,6181,71,Self-emp-not-inc,Prof-school,Married-civ-spouse,Farming-fishing,Husband,White,Male,2,United-States,<=50K
28,6847,67,Self-emp-not-inc,HS-grad,Married-civ-spouse,Adm-clerical,Wife,White,Female,2,United-States,<=50K
29,7028,64,None,Masters,Married-civ-spouse,None,Husband,White,Male,2,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...
32531,23227,51,Self-emp-not-inc,Assoc-acdm,Divorced,Exec-managerial,Unmarried,White,Female,99,United-States,<=50K
32532,23399,66,Private,Bachelors,Married-civ-spouse,Priv-house-serv,Other-relative,White,Male,99,United-States,<=50K
32533,23650,45,Private,Some-college,Married-civ-spouse,Sales,Husband,Black,Male,99,United-States,>50K
32534,23831,45,Self-emp-not-inc,Some-college,Married-civ-spouse,Other-service,Wife,White,Female,99,United-States,<=50K
32535,24484,39,Self-emp-inc,Masters,Divorced,Exec-managerial,Not-in-family,Asian-Pac-Islander,Male,99,Japan,>50K
32536,25355,65,Private,Masters,Never-married,Prof-specialty,Not-in-family,White,Male,99,United-States,<=50K
32537,25714,32,Private,Assoc-voc,Married-civ-spouse,Transport-moving,Husband,White,Male,99,United-States,>50K
32538,25807,49,None,7th-8th,Married-civ-spouse,None,Husband,White,Male,99,United-States,<=50K
32539,25832,31,Private,Doctorate,Married-civ-spouse,Prof-specialty,Husband,White,Male,99,United-States,>50K
32540,25987,44,Local-gov,Some-college,Married-civ-spouse,Protective-serv,Husband,Black,Male,99,United-States,<=50K
32541,26251,36,Self-emp-not-inc,Assoc-voc,Married-civ-spouse,Farming-fishing,Husband,White,Male,99,United-States,<=50K
32542,26597,35,Private,Assoc-acdm,Married-civ-spouse,Exec-managerial,Husband,White,Male,99,United-States,>50K
32543,26639,55,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,99,United-States,<=50K
32544,26859,66,Private,Bachelors,Married-civ-spouse,Prof-specialty,Husband,White,Male,99,United-States,<=50K
32545,27223,32,Local-gov,Some-college,Married-civ-spouse,Protective-serv,Husband,White,Male,99,United-States,<=50K
32546,27765,38,Self-emp-not-inc,Bachelors,Married-civ-spouse,Farming-fishing,Husband,White,Male,99,United-States,<=50K
32547,27810,30,Private,Some-college,Married-civ-spouse,Exec-managerial,Husband,Black,Male,99,United-States,<=50K
32548,28113,61,None,HS-grad,Divorced,None,Not-in-family,White,Female,99,United-States,<=50K
32549,29188,31,Private,HS-grad,Divorced,Other-service,Unmarried,White,Female,99,United-States,>50K
32550,29752,51,Self-emp-not-inc,12th,Married-civ-spouse,Other-service,Husband,White,Male,99,United-States,<=50K
32551,29990,43,Local-gov,Some-college,Married-civ-spouse,Tech-support,Husband,White,Male,99,United-States,>50K
32552,30037,40,Private,Bachelors,Married-civ-spouse,Prof-specialty,Husband,White,Male,99,United-States,>50K
32553,30611,51,Self-emp-not-inc,Some-college,Married-civ-spouse,Exec-managerial,Husband,White,Male,99,United-States,>50K
32554,30755,31,Private,Prof-school,Never-married,Prof-specialty,Not-in-family,White,Female,99,United-States,<=50K
32555,30767,42,Self-emp-not-inc,HS-grad,Married-civ-spouse,Farming-fishing,Husband,White,Male,99,United-States,>50K
32556,30993,40,Self-emp-inc,Masters,Never-married,Other-service,Own-child,White,Male,99,United-States,<=50K
32557,31682,43,Private,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,99,United-States,>50K
32558,31700,43,Self-emp-not-inc,Some-college,Married-civ-spouse,Farming-fishing,Husband,White,Male,99,United-States,<=50K
32559,32470,58,Self-emp-inc,Doctorate,Never-married,Prof-specialty,Not-in-family,White,Female,99,None,<=50K
32560,32532,30,None,Bachelors,Never-married,None,Not-in-family,Asian-Pac-Islander,Female,99,United-States,<=50K

In [19]:
query = 'select * from income_train ORDER BY "Hours.Per.Week" DESC'
pd.read_sql_query(query,conn)

,ID,Age,Workclass,Education,Marital.Status,Occupation,Relationship,Race,Sex,Hours.Per.Week,Native.Country,Income.Group
0,936,37,Private,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,99,United-States,>50K
1,1173,25,Private,Masters,Married-civ-spouse,Farming-fishing,Not-in-family,White,Male,99,United-States,>50K
2,1888,55,Self-emp-not-inc,Some-college,Married-civ-spouse,Farming-fishing,Husband,White,Male,99,United-States,>50K
3,3579,37,Self-emp-inc,Doctorate,Married-civ-spouse,Prof-specialty,Husband,Black,Male,99,United-States,>50K
4,4087,50,None,10th,Married-civ-spouse,None,Husband,White,Male,99,United-States,<=50K
5,4309,35,Self-emp-not-inc,HS-grad,Married-civ-spouse,Farming-fishing,Husband,White,Male,99,United-States,<=50K
6,4442,43,Self-emp-inc,Prof-school,Married-civ-spouse,Prof-specialty,Husband,Black,Male,99,United-States,>50K
7,5377,43,Private,Assoc-voc,Married-civ-spouse,Craft-repair,Husband,White,Male,99,United-States,<=50K
8,5433,44,Private,Prof-school,Divorced,Prof-specialty,Not-in-family,White,Female,99,United-States,<=50K
9,6619,27,Private,HS-grad,Married-civ-spouse,Transport-moving,Husband,White,Male,99,United-States,<=50K
10,6899,53,Self-emp-not-inc,10th,Married-spouse-absent,Transport-moving,Not-in-family,White,Male,99,United-States,<=50K
11,8073,44,Self-emp-not-inc,Assoc-acdm,Married-civ-spouse,Other-service,Wife,White,Female,99,United-States,<=50K
12,8394,50,Self-emp-inc,Some-college,Married-civ-spouse,Exec-managerial,Husband,White,Male,99,United-States,>50K
13,8655,30,Private,HS-grad,Never-married,Protective-serv,Not-in-family,White,Male,99,United-States,<=50K
14,8797,39,Private,Bachelors,Married-civ-spouse,Transport-moving,Husband,White,Male,99,United-States,>50K
15,9812,28,Private,Prof-school,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,99,Philippines,<=50K
16,9832,67,Private,Masters,Never-married,Prof-specialty,Not-in-family,White,Male,99,United-States,<=50K
17,10144,35,None,10th,Divorced,None,Not-in-family,White,Male,99,United-States,<=50K
18,10267,56,Self-emp-inc,9th,Married-civ-spouse,Transport-moving,Husband,White,Male,99,United-States,<=50K
19,10469,44,Self-emp-not-inc,Masters,Never-married,Farming-fishing,Own-child,White,Male,99,United-States,<=50K
20,10987,38,Private,HS-grad,Married-civ-spouse,Sales,Husband,White,Male,99,United-States,>50K
21,11834,58,Private,Bachelors,Never-married,Prof-specialty,Not-in-family,White,Male,99,United-States,<=50K
22,12210,53,Self-emp-not-inc,7th-8th,Married-civ-spouse,Tech-support,Husband,White,Male,99,United-States,<=50K
23,12626,51,Private,Doctorate,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,99,South,<=50K
24,12789,24,State-gov,Doctorate,Never-married,Prof-specialty,Not-in-family,White,Female,99,England,<=50K
25,13559,38,Private,Prof-school,Married-civ-spouse,Prof-specialty,Husband,White,Male,99,United-States,>50K
26,13581,38,Self-emp-not-inc,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,99,United-States,<=50K
27,13618,49,Private,10th,Separated,Exec-managerial,Not-in-family,Black,Male,99,United-States,<=50K
28,13859,37,Private,Doctorate,Married-civ-spouse,Prof-specialty,Husband,White,Male,99,France,>50K
29,14594,27,Private,Bachelors,Never-married,Exec-managerial,Own-child,White,Female,99,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...
32531,20609,72,None,HS-grad,Married-civ-spouse,None,Wife,White,Female,2,United-States,<=50K
32532,22131,67,None,Masters,Married-civ-spouse,None,Husband,White,Male,2,United-States,<=50K
32533,22388,22,None,Some-college,Never-married,None,Own-child,White,Male,2,United-States,<=50K
32534,23249,67,Private,Bachelors,Married-civ-spouse,Prof-specialty,Husband,White,Male,2,United-States,<=50K
32535,29098,68,None,9th,Married-civ-spouse,None,Husband,White,Male,2,United-States,<=50K
32536,29868,47,Private,Masters,Married-civ-spouse,Prof-specialty,Wife,White,Female,2,United-States,>50K
32537,30003,18,Private,11th,Never-married,Prof-specialty,Own-child,White,Female,2,United-States,<=50K
32538,30201,36,Private,HS-grad,Married-civ-spouse,Other-service,Wife,Asian-Pac-Islander,Female,2,Taiwan,<=50K
32539,31391,61,None,Masters,Married-civ-spouse,None,Husband,White,Male,2,United-States,>50K
32540,31433,87,None,HS-grad,Widowed,None,Not-in-family,White,Male,2,United-States,<=50K
32541,190,58,State-gov,Doctorate,Married-civ-spouse,Prof-specialty,Husband,White,Male,1,United-States,>50K
32542,1037,66,Self-emp-inc,9th,Married-civ-spouse,Exec-managerial,Husband,White,Male,1,None,<=50K
32543,1263,69,None,Assoc-voc,Widowed,None,Not-in-family,White,Female,1,United-States,<=50K
32544,5591,78,None,HS-grad,Widowed,None,Not-in-family,White,Female,1,United-States,<=50K
32545,5633,45,None,Masters,Married-civ-spouse,None,Wife,White,Female,1,United-States,<=50K
32546,5767,62,None,Some-college,Married-civ-spouse,None,Wife,White,Female,1,United-States,<=50K
32547,5809,76,None,10th,Married-civ-spouse,None,Husband,White,Male,1,United-States,<=50K
32548,8448,67,None,Assoc-voc,Widowed,None,Not-in-family,White,Female,1,United-States,<=50K
32549,9148,75,None,10th,Widowed,None,Other-relative,Asian-Pac-Islander,Female,1,China,<=50K
32550,11452,27,Private,HS-grad,Never-married,Machine-op-inspct,Other-relative,White,Male,1,United-States,<=50K
32551,19338,72,None,HS-grad,Married-civ-spouse,None,Husband,Asian-Pac-Islander,Male,1,United-States,<=50K
32552,19751,23,Private,HS-grad,Never-married,Craft-repair,Own-child,Asian-Pac-Islander,Male,1,Vietnam,<=50K
32553,20073,65,None,HS-grad,Married-civ-spouse,None,Husband,White,Male,1,United-States,>50K
32554,20910,77,Self-emp-not-inc,Some-college,Widowed,Adm-clerical,Not-in-family,White,Female,1,United-States,<=50K
32555,22961,21,Private,HS-grad,Never-married,Machine-op-inspct,Own-child,Black,Male,1,United-States,<=50K
32556,23537,69,None,Some-college,Never-married,None,Not-in-family,White,Male,1,United-States,<=50K
32557,24285,57,Self-emp-not-inc,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,1,United-States,<=50K
32558,25079,74,Private,10th,Divorced,Other-service,Not-in-family,White,Female,1,United-States,<=50K
32559,29753,69,None,Assoc-acdm,Divorced,None,Unmarried,White,Female,1,United-States,<=50K
32560,32526,81,None,Assoc-voc,Divorced,None,Unmarried,White,Female,1,None,<=50K

In [21]:
query = 'select * from income_train ORDER BY "Hours.Per.Week","Age"DESC'
pd.read_sql_query(query,conn)

,ID,Age,Workclass,Education,Marital.Status,Occupation,Relationship,Race,Sex,Hours.Per.Week,Native.Country,Income.Group
0,32526,81,None,Assoc-voc,Divorced,None,Unmarried,White,Female,1,None,<=50K
1,5591,78,None,HS-grad,Widowed,None,Not-in-family,White,Female,1,United-States,<=50K
2,20910,77,Self-emp-not-inc,Some-college,Widowed,Adm-clerical,Not-in-family,White,Female,1,United-States,<=50K
3,5809,76,None,10th,Married-civ-spouse,None,Husband,White,Male,1,United-States,<=50K
4,9148,75,None,10th,Widowed,None,Other-relative,Asian-Pac-Islander,Female,1,China,<=50K
5,25079,74,Private,10th,Divorced,Other-service,Not-in-family,White,Female,1,United-States,<=50K
6,19338,72,None,HS-grad,Married-civ-spouse,None,Husband,Asian-Pac-Islander,Male,1,United-States,<=50K
7,1263,69,None,Assoc-voc,Widowed,None,Not-in-family,White,Female,1,United-States,<=50K
8,23537,69,None,Some-college,Never-married,None,Not-in-family,White,Male,1,United-States,<=50K
9,29753,69,None,Assoc-acdm,Divorced,None,Unmarried,White,Female,1,United-States,<=50K
10,8448,67,None,Assoc-voc,Widowed,None,Not-in-family,White,Female,1,United-States,<=50K
11,1037,66,Self-emp-inc,9th,Married-civ-spouse,Exec-managerial,Husband,White,Male,1,None,<=50K
12,20073,65,None,HS-grad,Married-civ-spouse,None,Husband,White,Male,1,United-States,>50K
13,5767,62,None,Some-college,Married-civ-spouse,None,Wife,White,Female,1,United-States,<=50K
14,190,58,State-gov,Doctorate,Married-civ-spouse,Prof-specialty,Husband,White,Male,1,United-States,>50K
15,24285,57,Self-emp-not-inc,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,1,United-States,<=50K
16,5633,45,None,Masters,Married-civ-spouse,None,Wife,White,Female,1,United-States,<=50K
17,11452,27,Private,HS-grad,Never-married,Machine-op-inspct,Other-relative,White,Male,1,United-States,<=50K
18,19751,23,Private,HS-grad,Never-married,Craft-repair,Own-child,Asian-Pac-Islander,Male,1,Vietnam,<=50K
19,22961,21,Private,HS-grad,Never-married,Machine-op-inspct,Own-child,Black,Male,1,United-States,<=50K
20,31433,87,None,HS-grad,Widowed,None,Not-in-family,White,Male,2,United-States,<=50K
21,8432,82,Private,7th-8th,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,2,United-States,<=50K
22,13027,79,None,Assoc-acdm,Married-civ-spouse,None,Wife,White,Female,2,United-States,>50K
23,1035,76,None,7th-8th,Widowed,None,Not-in-family,White,Male,2,United-States,<=50K
24,1459,76,None,HS-grad,Widowed,None,Not-in-family,Black,Female,2,United-States,<=50K
25,3292,74,None,7th-8th,Married-civ-spouse,None,Husband,White,Male,2,United-States,<=50K
26,20609,72,None,HS-grad,Married-civ-spouse,None,Wife,White,Female,2,United-States,<=50K
27,158,71,Self-emp-not-inc,Some-college,Separated,Sales,Unmarried,Black,Male,2,United-States,<=50K
28,6181,71,Self-emp-not-inc,Prof-school,Married-civ-spouse,Farming-fishing,Husband,White,Male,2,United-States,<=50K
29,29098,68,None,9th,Married-civ-spouse,None,Husband,White,Male,2,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...
32531,936,37,Private,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,99,United-States,>50K
32532,3579,37,Self-emp-inc,Doctorate,Married-civ-spouse,Prof-specialty,Husband,Black,Male,99,United-States,>50K
32533,13859,37,Private,Doctorate,Married-civ-spouse,Prof-specialty,Husband,White,Male,99,France,>50K
32534,15461,37,Private,Bachelors,Married-civ-spouse,Prof-specialty,Husband,White,Male,99,United-States,>50K
32535,26251,36,Self-emp-not-inc,Assoc-voc,Married-civ-spouse,Farming-fishing,Husband,White,Male,99,United-States,<=50K
32536,4309,35,Self-emp-not-inc,HS-grad,Married-civ-spouse,Farming-fishing,Husband,White,Male,99,United-States,<=50K
32537,10144,35,None,10th,Divorced,None,Not-in-family,White,Male,99,United-States,<=50K
32538,26597,35,Private,Assoc-acdm,Married-civ-spouse,Exec-managerial,Husband,White,Male,99,United-States,>50K
32539,19732,34,Federal-gov,Doctorate,Never-married,Prof-specialty,Not-in-family,White,Female,99,United-States,<=50K
32540,18604,33,Self-emp-not-inc,Assoc-voc,Divorced,Other-service,Unmarried,White,Female,99,United-States,<=50K
32541,25714,32,Private,Assoc-voc,Married-civ-spouse,Transport-moving,Husband,White,Male,99,United-States,>50K
32542,27223,32,Local-gov,Some-college,Married-civ-spouse,Protective-serv,Husband,White,Male,99,United-States,<=50K
32543,23180,31,Private,HS-grad,Never-married,Farming-fishing,Not-in-family,White,Male,99,United-States,<=50K
32544,25832,31,Private,Doctorate,Married-civ-spouse,Prof-specialty,Husband,White,Male,99,United-States,>50K
32545,29188,31,Private,HS-grad,Divorced,Other-service,Unmarried,White,Female,99,United-States,>50K
32546,30755,31,Private,Prof-school,Never-married,Prof-specialty,Not-in-family,White,Female,99,United-States,<=50K
32547,8655,30,Private,HS-grad,Never-married,Protective-serv,Not-in-family,White,Male,99,United-States,<=50K
32548,27810,30,Private,Some-college,Married-civ-spouse,Exec-managerial,Husband,Black,Male,99,United-States,<=50K
32549,32532,30,None,Bachelors,Never-married,None,Not-in-family,Asian-Pac-Islander,Female,99,United-States,<=50K
32550,15535,29,Private,HS-grad,Divorced,Other-service,Unmarried,White,Female,99,United-States,<=50K
32551,9812,28,Private,Prof-school,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,99,Philippines,<=50K
32552,17612,28,Self-emp-not-inc,7th-8th,Never-married,Other-service,Other-relative,White,Female,99,Mexico,<=50K
32553,6619,27,Private,HS-grad,Married-civ-spouse,Transport-moving,Husband,White,Male,99,United-States,<=50K
32554,14594,27,Private,Bachelors,Never-married,Exec-managerial,Own-child,White,Female,99,United-States,<=50K
32555,19054,27,Private,HS-grad,Never-married,Transport-moving,Not-in-family,White,Male,99,United-States,<=50K
32556,22314,26,Self-emp-not-inc,10th,Married-civ-spouse,Farming-fishing,Husband,White,Male,99,United-States,<=50K
32557,1173,25,Private,Masters,Married-civ-spouse,Farming-fishing,Not-in-family,White,Male,99,United-States,>50K
32558,15181,25,Private,11th,Never-married,Other-service,Not-in-family,White,Male,99,United-States,<=50K
32559,12789,24,State-gov,Doctorate,Never-married,Prof-specialty,Not-in-family,White,Female,99,England,<=50K
32560,16993,19,Private,7th-8th,Married-civ-spouse,Craft-repair,Husband,White,Male,99,United-States,<=50K

In [22]:
query = 'select * from income_train ORDER BY "Hours.Per.Week"DESC , "Age"DESC'
pd.read_sql_query(query,conn)

,ID,Age,Workclass,Education,Marital.Status,Occupation,Relationship,Race,Sex,Hours.Per.Week,Native.Country,Income.Group
0,15357,90,Private,HS-grad,Widowed,Transport-moving,Unmarried,White,Male,99,United-States,<=50K
1,16605,73,Self-emp-not-inc,7th-8th,Married-civ-spouse,Farming-fishing,Husband,White,Male,99,United-States,>50K
2,19998,72,Private,7th-8th,Widowed,Other-service,Not-in-family,White,Female,99,None,<=50K
3,9832,67,Private,Masters,Never-married,Prof-specialty,Not-in-family,White,Male,99,United-States,<=50K
4,23399,66,Private,Bachelors,Married-civ-spouse,Priv-house-serv,Other-relative,White,Male,99,United-States,<=50K
5,26859,66,Private,Bachelors,Married-civ-spouse,Prof-specialty,Husband,White,Male,99,United-States,<=50K
6,25355,65,Private,Masters,Never-married,Prof-specialty,Not-in-family,White,Male,99,United-States,<=50K
7,21057,64,Local-gov,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,99,United-States,<=50K
8,15017,62,Private,HS-grad,Divorced,Priv-house-serv,Unmarried,Black,Female,99,United-States,<=50K
9,20037,61,Self-emp-inc,Masters,Widowed,Exec-managerial,Unmarried,White,Female,99,United-States,<=50K
10,28113,61,None,HS-grad,Divorced,None,Not-in-family,White,Female,99,United-States,<=50K
11,19142,59,Private,7th-8th,Married-civ-spouse,Other-service,Wife,White,Female,99,United-States,<=50K
12,11834,58,Private,Bachelors,Never-married,Prof-specialty,Not-in-family,White,Male,99,United-States,<=50K
13,32470,58,Self-emp-inc,Doctorate,Never-married,Prof-specialty,Not-in-family,White,Female,99,None,<=50K
14,10267,56,Self-emp-inc,9th,Married-civ-spouse,Transport-moving,Husband,White,Male,99,United-States,<=50K
15,1888,55,Self-emp-not-inc,Some-college,Married-civ-spouse,Farming-fishing,Husband,White,Male,99,United-States,>50K
16,22558,55,Self-emp-not-inc,Some-college,Married-civ-spouse,Transport-moving,Husband,White,Male,99,United-States,<=50K
17,26639,55,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,99,United-States,<=50K
18,6899,53,Self-emp-not-inc,10th,Married-spouse-absent,Transport-moving,Not-in-family,White,Male,99,United-States,<=50K
19,12210,53,Self-emp-not-inc,7th-8th,Married-civ-spouse,Tech-support,Husband,White,Male,99,United-States,<=50K
20,16869,53,Private,Assoc-acdm,Married-civ-spouse,Exec-managerial,Husband,White,Male,99,United-States,<=50K
21,12626,51,Private,Doctorate,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,99,South,<=50K
22,23227,51,Self-emp-not-inc,Assoc-acdm,Divorced,Exec-managerial,Unmarried,White,Female,99,United-States,<=50K
23,29752,51,Self-emp-not-inc,12th,Married-civ-spouse,Other-service,Husband,White,Male,99,United-States,<=50K
24,30611,51,Self-emp-not-inc,Some-college,Married-civ-spouse,Exec-managerial,Husband,White,Male,99,United-States,>50K
25,4087,50,None,10th,Married-civ-spouse,None,Husband,White,Male,99,United-States,<=50K
26,8394,50,Self-emp-inc,Some-college,Married-civ-spouse,Exec-managerial,Husband,White,Male,99,United-States,>50K
27,13618,49,Private,10th,Separated,Exec-managerial,Not-in-family,Black,Male,99,United-States,<=50K
28,25807,49,None,7th-8th,Married-civ-spouse,None,Husband,White,Male,99,United-States,<=50K
29,22217,45,Private,Some-college,Divorced,Craft-repair,Unmarried,White,Male,99,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...
32531,13371,38,None,Masters,Married-civ-spouse,None,Wife,Black,Female,2,United-States,>50K
32532,30201,36,Private,HS-grad,Married-civ-spouse,Other-service,Wife,Asian-Pac-Islander,Female,2,Taiwan,<=50K
32533,2933,32,None,Assoc-voc,Never-married,None,Unmarried,White,Female,2,United-States,<=50K
32534,5173,32,None,HS-grad,Married-civ-spouse,None,Wife,White,Female,2,United-States,>50K
32535,14646,32,Private,Bachelors,Married-civ-spouse,Adm-clerical,Wife,White,Female,2,United-States,<=50K
32536,11788,27,Private,Bachelors,Never-married,Sales,Own-child,White,Male,2,United-States,<=50K
32537,19428,24,Local-gov,Assoc-acdm,Never-married,Prof-specialty,Own-child,White,Female,2,United-States,<=50K
32538,22388,22,None,Some-college,Never-married,None,Own-child,White,Male,2,United-States,<=50K
32539,13988,20,Private,Some-college,Never-married,Prof-specialty,Own-child,White,Female,2,United-States,<=50K
32540,30003,18,Private,11th,Never-married,Prof-specialty,Own-child,White,Female,2,United-States,<=50K
32541,32526,81,None,Assoc-voc,Divorced,None,Unmarried,White,Female,1,None,<=50K
32542,5591,78,None,HS-grad,Widowed,None,Not-in-family,White,Female,1,United-States,<=50K
32543,20910,77,Self-emp-not-inc,Some-college,Widowed,Adm-clerical,Not-in-family,White,Female,1,United-States,<=50K
32544,5809,76,None,10th,Married-civ-spouse,None,Husband,White,Male,1,United-States,<=50K
32545,9148,75,None,10th,Widowed,None,Other-relative,Asian-Pac-Islander,Female,1,China,<=50K
32546,25079,74,Private,10th,Divorced,Other-service,Not-in-family,White,Female,1,United-States,<=50K
32547,19338,72,None,HS-grad,Married-civ-spouse,None,Husband,Asian-Pac-Islander,Male,1,United-States,<=50K
32548,1263,69,None,Assoc-voc,Widowed,None,Not-in-family,White,Female,1,United-States,<=50K
32549,23537,69,None,Some-college,Never-married,None,Not-in-family,White,Male,1,United-States,<=50K
32550,29753,69,None,Assoc-acdm,Divorced,None,Unmarried,White,Female,1,United-States,<=50K
32551,8448,67,None,Assoc-voc,Widowed,None,Not-in-family,White,Female,1,United-States,<=50K
32552,1037,66,Self-emp-inc,9th,Married-civ-spouse,Exec-managerial,Husband,White,Male,1,None,<=50K
32553,20073,65,None,HS-grad,Married-civ-spouse,None,Husband,White,Male,1,United-States,>50K
32554,5767,62,None,Some-college,Married-civ-spouse,None,Wife,White,Female,1,United-States,<=50K
32555,190,58,State-gov,Doctorate,Married-civ-spouse,Prof-specialty,Husband,White,Male,1,United-States,>50K
32556,24285,57,Self-emp-not-inc,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,1,United-States,<=50K
32557,5633,45,None,Masters,Married-civ-spouse,None,Wife,White,Female,1,United-States,<=50K
32558,11452,27,Private,HS-grad,Never-married,Machine-op-inspct,Other-relative,White,Male,1,United-States,<=50K
32559,19751,23,Private,HS-grad,Never-married,Craft-repair,Own-child,Asian-Pac-Islander,Male,1,Vietnam,<=50K
32560,22961,21,Private,HS-grad,Never-married,Machine-op-inspct,Own-child,Black,Male,1,United-States,<=50K